
REPORT ZAR_CALLING_USUAL_ABAP_CLASS.

TABLES: VBAK.

TYPES: BEGIN OF TY_VBAK,
         VBELN TYPE VBAK-VBELN,  "Sales document number
         ERDAT TYPE VBAK-ERDAT,   "created date (date)
         ERNAM TYPE VBAK-ERNAM,   "created by (user)
         AUART TYPE VBAK-AUART,   "sales document type
         VKORG TYPE VBAK-VKORG,   "sales organization
         VTWEG TYPE VBAK-VTWEG,   " Distribution Channel
         SPART TYPE VBAK-SPART,   " Division
         KUNNR TYPE VBAK-KUNNR,   " Sold-to Party (Customer Number)
         NETWR TYPE VBAK-NETWR,   " Net Value
         WAERK TYPE VBAK-WAERK,   " Currency
       END OF TY_VBAK.


"work ares and internal tables
DATA: IT_VBAK TYPE STANDARD TABLE OF TY_VBAK,
      WA_VBAK TYPE TY_VBAK.

DATA: IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

SELECT VBELN ERDAT ERNAM AUART VKORG VTWEG SPART KUNNR NETWR WAERK
  FROM VBAK
  INTO TABLE IT_VBAK
  UP TO 30 ROWS.

WA_FIELDCAT-COL_POS = 1.
WA_FIELDCAT-FIELDNAME = 'VBELN'.
WA_FIELDCAT-SELTEXT_M = 'Sales Order'.
WA_FIELDCAT-KEY = 'X'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 2.
WA_FIELDCAT-FIELDNAME = 'ERDAT'.
WA_FIELDCAT-SELTEXT_M = 'created date'.
WA_FIELDCAT-DATATYPE = 'DATS'.  " Show as date
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 3.
WA_FIELDCAT-FIELDNAME = 'ERNAM'.
WA_FIELDCAT-SELTEXT_M = 'created by'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 4.
WA_FIELDCAT-FIELDNAME = 'AUART'.
WA_FIELDCAT-SELTEXT_M = 'sales Document Type'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 5.
WA_FIELDCAT-FIELDNAME = 'VKORG'.
WA_FIELDCAT-SELTEXT_M = 'Sales organization'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 6.
WA_FIELDCAT-FIELDNAME = 'VTWEG'.
WA_FIELDCAT-SELTEXT_M = 'Distribution channel'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 7.
WA_FIELDCAT-FIELDNAME = 'SPART'.
WA_FIELDCAT-SELTEXT_M = 'division'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 8.
WA_FIELDCAT-FIELDNAME = 'KUNNR'.
WA_FIELDCAT-SELTEXT_M = 'sold to party'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 9.
WA_FIELDCAT-FIELDNAME = 'NETWR'.
WA_FIELDCAT-SELTEXT_M = 'net value'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.

CLEAR WA_FIELDCAT.
WA_FIELDCAT-COL_POS = 10.
WA_FIELDCAT-FIELDNAME = 'WAERK'.
WA_FIELDCAT-SELTEXT_M = 'Currency'.
APPEND WA_FIELDCAT TO IT_FIELDCAT.


CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    IT_FIELDCAT = IT_FIELDCAT
    I_SAVE      = 'A'        " Allow layout save
  TABLES
    T_OUTTAB    = IT_VBAK.
